# Generated by Django 4.0.3 on 2022-03-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=50, verbose_name='Nome Empresa')),
                ('symbol_stock', models.CharField(max_length=10, verbose_name='Símbolo Empresa')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('date_modify', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
