# Generated by Django 4.0.3 on 2022-04-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='data_entrada',
            field=models.CharField(default=1, max_length=15, verbose_name='Data Entrada'),
            preserve_default=False,
        ),
    ]
