# Generated by Django 4.0.3 on 2022-05-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0003_stock_data_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='LucroLiquido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_stock', models.CharField(max_length=10, verbose_name='Símbolo Empresa')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('lucro_liquido', models.FloatField(verbose_name='Lucro Líquido')),
            ],
        ),
    ]
