# Generated by Django 4.0.3 on 2022-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0004_lucroliquido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name_stock',
            field=models.CharField(max_length=150, verbose_name='Nome Empresa'),
        ),
    ]
