# Generated by Django 4.0.3 on 2022-07-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0006_pricedatastock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedatastock',
            old_name='name_stoke',
            new_name='symbol_stock',
        ),
    ]
