# Generated by Django 4.0.3 on 2022-07-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0007_rename_name_stoke_pricedatastock_symbol_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricedatastock',
            old_name='symbol_stock',
            new_name='stock',
        ),
    ]
