# Generated by Django 4.0.3 on 2022-07-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0008_rename_symbol_stock_pricedatastock_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceDataStock',
            new_name='PriceDataStocks',
        ),
    ]
