# Generated by Django 4.0.3 on 2022-07-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0009_rename_pricedatastock_pricedatastocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceDataStocks',
        ),
    ]
