# Generated by Django 4.0.3 on 2022-07-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0011_pricedatastocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDataStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ref', models.DateField(verbose_name='Data Referência')),
                ('dividends', models.FloatField(verbose_name='Dividendos pago')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockanalysis.stock')),
            ],
        ),
    ]
